/**
 * PodcastModern API
 * PodcastModern API documentation
 * <p>
 * OpenAPI spec version: 0.0.1
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.javathlon.apiclient.model;

import com.google.gson.annotations.SerializedName;

import org.joda.time.DateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;


/**
 * ApplicationDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T13:50:52.801+04:00")
public class ApplicationDTO {
    @SerializedName("createdBy")
    private String createdBy = null;

    @SerializedName("createdDate")
    private DateTime createdDate = null;

    @SerializedName("creators")
    private List<UserDTO> creators = new ArrayList<UserDTO>();

    @SerializedName("description")
    private String description = null;

    @SerializedName("id")
    private Long id = null;

    @SerializedName("lastModifiedBy")
    private String lastModifiedBy = null;

    @SerializedName("lastModifiedDate")
    private DateTime lastModifiedDate = null;

    @SerializedName("logo")
    private String logo = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("coverImage")
    private String coverImage;

    @SerializedName("coverVideo")
    private String coverVideo;

    @SerializedName("podcasts")
    private List<PodcastDTO> podcasts = new ArrayList<PodcastDTO>();

    @SerializedName("subscriptionItems")
    private List<SubscriptionItemDTO> subscriptionItems = new ArrayList<SubscriptionItemDTO>();

    public ApplicationDTO createdBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Get createdBy
     * @return createdBy
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public ApplicationDTO createdDate(DateTime createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Get createdDate
     * @return createdDate
     **/
    @ApiModelProperty(example = "null", value = "")
    public DateTime getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(DateTime createdDate) {
        this.createdDate = createdDate;
    }

    public ApplicationDTO creators(List<UserDTO> creators) {
        this.creators = creators;
        return this;
    }

    public ApplicationDTO addCreatorsItem(UserDTO creatorsItem) {
        this.creators.add(creatorsItem);
        return this;
    }

    /**
     * Get creators
     * @return creators
     **/
    @ApiModelProperty(example = "null", value = "")
    public List<UserDTO> getCreators() {
        return creators;
    }

    public void setCreators(List<UserDTO> creators) {
        this.creators = creators;
    }

    public ApplicationDTO description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     * @return description
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public ApplicationDTO id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * @return id
     **/
    @ApiModelProperty(example = "null", value = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public ApplicationDTO lastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
        return this;
    }

    /**
     * Get lastModifiedBy
     * @return lastModifiedBy
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public ApplicationDTO lastModifiedDate(DateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
        return this;
    }

    /**
     * Get lastModifiedDate
     * @return lastModifiedDate
     **/
    @ApiModelProperty(example = "null", value = "")
    public DateTime getLastModifiedDate() {
        return lastModifiedDate;
    }

    public void setLastModifiedDate(DateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    public ApplicationDTO logo(String logo) {
        this.logo = logo;
        return this;
    }

    /**
     * Get logo
     * @return logo
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getLogo() {
        return logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    public ApplicationDTO name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     * @return name
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public ApplicationDTO podcasts(List<PodcastDTO> podcasts) {
        this.podcasts = podcasts;
        return this;
    }

    public ApplicationDTO addPodcastsItem(PodcastDTO podcastsItem) {
        this.podcasts.add(podcastsItem);
        return this;
    }

    public String getCoverImage() {
        return coverImage;
    }

    public void setCoverImage(String coverImage) {
        this.coverImage = coverImage;
    }

    public String getCoverVideo() {
        return coverVideo;
    }

    public void setCoverVideo(String coverVideo) {
        this.coverVideo = coverVideo;
    }

    /**
     * Get podcasts
     * @return podcasts
     **/
    @ApiModelProperty(example = "null", value = "")
    public List<PodcastDTO> getPodcasts() {
        return podcasts;
    }

    public void setPodcasts(List<PodcastDTO> podcasts) {
        this.podcasts = podcasts;
    }

    public ApplicationDTO subscriptionItems(List<SubscriptionItemDTO> subscriptionItems) {
        this.subscriptionItems = subscriptionItems;
        return this;
    }

    public ApplicationDTO addSubscriptionItemsItem(SubscriptionItemDTO subscriptionItemsItem) {
        this.subscriptionItems.add(subscriptionItemsItem);
        return this;
    }

    /**
     * Get subscriptionItems
     * @return subscriptionItems
     **/
    @ApiModelProperty(example = "null", value = "")
    public List<SubscriptionItemDTO> getSubscriptionItems() {
        return subscriptionItems;
    }

    public void setSubscriptionItems(List<SubscriptionItemDTO> subscriptionItems) {
        this.subscriptionItems = subscriptionItems;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ApplicationDTO applicationDTO = (ApplicationDTO) o;
        return Objects.equals(this.createdBy, applicationDTO.createdBy) &&
                Objects.equals(this.createdDate, applicationDTO.createdDate) &&
                Objects.equals(this.creators, applicationDTO.creators) &&
                Objects.equals(this.description, applicationDTO.description) &&
                Objects.equals(this.id, applicationDTO.id) &&
                Objects.equals(this.lastModifiedBy, applicationDTO.lastModifiedBy) &&
                Objects.equals(this.lastModifiedDate, applicationDTO.lastModifiedDate) &&
                Objects.equals(this.logo, applicationDTO.logo) &&
                Objects.equals(this.name, applicationDTO.name) &&
                Objects.equals(this.podcasts, applicationDTO.podcasts) &&
                Objects.equals(this.subscriptionItems, applicationDTO.subscriptionItems);
    }

    @Override
    public int hashCode() {
        return Objects.hash(createdBy, createdDate, creators, description, id, lastModifiedBy, lastModifiedDate, logo, name, podcasts, subscriptionItems);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ApplicationDTO {\n");

        sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
        sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
        sb.append("    creators: ").append(toIndentedString(creators)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
        sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");
        sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    podcasts: ").append(toIndentedString(podcasts)).append("\n");
        sb.append("    subscriptionItems: ").append(toIndentedString(subscriptionItems)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

