/**
 * PodcastModern API
 * PodcastModern API documentation
 * <p>
 * OpenAPI spec version: 0.0.1
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.javathlon.apiclient.model;

import com.google.gson.annotations.SerializedName;

import org.joda.time.DateTime;
import org.joda.time.LocalDate;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;


/**
 * ApplicationSubscriber
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-05T16:35:00.407+04:00")
public class ApplicationSubscriber {
    @SerializedName("active")
    private Boolean active = null;

    @SerializedName("application")
    private Application application = null;

    @SerializedName("createdBy")
    private String createdBy = null;

    @SerializedName("createdDate")
    private DateTime createdDate = null;

    @SerializedName("id")
    private Long id = null;

    @SerializedName("lastModifiedBy")
    private String lastModifiedBy = null;

    @SerializedName("lastModifiedDate")
    private DateTime lastModifiedDate = null;

    @SerializedName("subscribeDate")
    private LocalDate subscribeDate = null;

    @SerializedName("subscriber")
    private Subscriber subscriber = null;

    public ApplicationSubscriber active(Boolean active) {
        this.active = active;
        return this;
    }

    /**
     * Get active
     * @return active
     **/
    @ApiModelProperty(example = "null", value = "")
    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public ApplicationSubscriber application(Application application) {
        this.application = application;
        return this;
    }

    /**
     * Get application
     * @return application
     **/
    @ApiModelProperty(example = "null", value = "")
    public Application getApplication() {
        return application;
    }

    public void setApplication(Application application) {
        this.application = application;
    }

    public ApplicationSubscriber createdBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Get createdBy
     * @return createdBy
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public ApplicationSubscriber createdDate(DateTime createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Get createdDate
     * @return createdDate
     **/
    @ApiModelProperty(example = "null", value = "")
    public DateTime getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(DateTime createdDate) {
        this.createdDate = createdDate;
    }

    public ApplicationSubscriber id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * @return id
     **/
    @ApiModelProperty(example = "null", value = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public ApplicationSubscriber lastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
        return this;
    }

    /**
     * Get lastModifiedBy
     * @return lastModifiedBy
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public ApplicationSubscriber lastModifiedDate(DateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
        return this;
    }

    /**
     * Get lastModifiedDate
     * @return lastModifiedDate
     **/
    @ApiModelProperty(example = "null", value = "")
    public DateTime getLastModifiedDate() {
        return lastModifiedDate;
    }

    public void setLastModifiedDate(DateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    public ApplicationSubscriber subscribeDate(LocalDate subscribeDate) {
        this.subscribeDate = subscribeDate;
        return this;
    }

    /**
     * Get subscribeDate
     * @return subscribeDate
     **/
    @ApiModelProperty(example = "null", value = "")
    public LocalDate getSubscribeDate() {
        return subscribeDate;
    }

    public void setSubscribeDate(LocalDate subscribeDate) {
        this.subscribeDate = subscribeDate;
    }

    public ApplicationSubscriber subscriber(Subscriber subscriber) {
        this.subscriber = subscriber;
        return this;
    }

    /**
     * Get subscriber
     * @return subscriber
     **/
    @ApiModelProperty(example = "null", value = "")
    public Subscriber getSubscriber() {
        return subscriber;
    }

    public void setSubscriber(Subscriber subscriber) {
        this.subscriber = subscriber;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ApplicationSubscriber applicationSubscriber = (ApplicationSubscriber) o;
        return Objects.equals(this.active, applicationSubscriber.active) &&
                Objects.equals(this.application, applicationSubscriber.application) &&
                Objects.equals(this.createdBy, applicationSubscriber.createdBy) &&
                Objects.equals(this.createdDate, applicationSubscriber.createdDate) &&
                Objects.equals(this.id, applicationSubscriber.id) &&
                Objects.equals(this.lastModifiedBy, applicationSubscriber.lastModifiedBy) &&
                Objects.equals(this.lastModifiedDate, applicationSubscriber.lastModifiedDate) &&
                Objects.equals(this.subscribeDate, applicationSubscriber.subscribeDate) &&
                Objects.equals(this.subscriber, applicationSubscriber.subscriber);
    }

    @Override
    public int hashCode() {
        return Objects.hash(active, application, createdBy, createdDate, id, lastModifiedBy, lastModifiedDate, subscribeDate, subscriber);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ApplicationSubscriber {\n");

        sb.append("    active: ").append(toIndentedString(active)).append("\n");
        sb.append("    application: ").append(toIndentedString(application)).append("\n");
        sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
        sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
        sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");
        sb.append("    subscribeDate: ").append(toIndentedString(subscribeDate)).append("\n");
        sb.append("    subscriber: ").append(toIndentedString(subscriber)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

