/**
 * PodcastModern API
 * PodcastModern API documentation
 * <p>
 * OpenAPI spec version: 0.0.1
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.javathlon.apiclient.model;

import com.google.gson.annotations.SerializedName;

import org.joda.time.DateTime;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;


/**
 * EntityAuditEvent
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T13:50:52.801+04:00")
public class EntityAuditEvent {
    @SerializedName("action")
    private String action = null;

    @SerializedName("commitVersion")
    private Integer commitVersion = null;

    @SerializedName("entityId")
    private Long entityId = null;

    @SerializedName("entityType")
    private String entityType = null;

    @SerializedName("entityValue")
    private String entityValue = null;

    @SerializedName("id")
    private Long id = null;

    @SerializedName("modifiedBy")
    private String modifiedBy = null;

    @SerializedName("modifiedDate")
    private DateTime modifiedDate = null;

    public EntityAuditEvent action(String action) {
        this.action = action;
        return this;
    }

    /**
     * Get action
     * @return action
     **/
    @ApiModelProperty(example = "null", required = true, value = "")
    public String getAction() {
        return action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public EntityAuditEvent commitVersion(Integer commitVersion) {
        this.commitVersion = commitVersion;
        return this;
    }

    /**
     * Get commitVersion
     * @return commitVersion
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getCommitVersion() {
        return commitVersion;
    }

    public void setCommitVersion(Integer commitVersion) {
        this.commitVersion = commitVersion;
    }

    public EntityAuditEvent entityId(Long entityId) {
        this.entityId = entityId;
        return this;
    }

    /**
     * Get entityId
     * @return entityId
     **/
    @ApiModelProperty(example = "null", required = true, value = "")
    public Long getEntityId() {
        return entityId;
    }

    public void setEntityId(Long entityId) {
        this.entityId = entityId;
    }

    public EntityAuditEvent entityType(String entityType) {
        this.entityType = entityType;
        return this;
    }

    /**
     * Get entityType
     * @return entityType
     **/
    @ApiModelProperty(example = "null", required = true, value = "")
    public String getEntityType() {
        return entityType;
    }

    public void setEntityType(String entityType) {
        this.entityType = entityType;
    }

    public EntityAuditEvent entityValue(String entityValue) {
        this.entityValue = entityValue;
        return this;
    }

    /**
     * Get entityValue
     * @return entityValue
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getEntityValue() {
        return entityValue;
    }

    public void setEntityValue(String entityValue) {
        this.entityValue = entityValue;
    }

    public EntityAuditEvent id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * @return id
     **/
    @ApiModelProperty(example = "null", value = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public EntityAuditEvent modifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
        return this;
    }

    /**
     * Get modifiedBy
     * @return modifiedBy
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getModifiedBy() {
        return modifiedBy;
    }

    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    public EntityAuditEvent modifiedDate(DateTime modifiedDate) {
        this.modifiedDate = modifiedDate;
        return this;
    }

    /**
     * Get modifiedDate
     * @return modifiedDate
     **/
    @ApiModelProperty(example = "null", required = true, value = "")
    public DateTime getModifiedDate() {
        return modifiedDate;
    }

    public void setModifiedDate(DateTime modifiedDate) {
        this.modifiedDate = modifiedDate;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EntityAuditEvent entityAuditEvent = (EntityAuditEvent) o;
        return Objects.equals(this.action, entityAuditEvent.action) &&
                Objects.equals(this.commitVersion, entityAuditEvent.commitVersion) &&
                Objects.equals(this.entityId, entityAuditEvent.entityId) &&
                Objects.equals(this.entityType, entityAuditEvent.entityType) &&
                Objects.equals(this.entityValue, entityAuditEvent.entityValue) &&
                Objects.equals(this.id, entityAuditEvent.id) &&
                Objects.equals(this.modifiedBy, entityAuditEvent.modifiedBy) &&
                Objects.equals(this.modifiedDate, entityAuditEvent.modifiedDate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(action, commitVersion, entityId, entityType, entityValue, id, modifiedBy, modifiedDate);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class EntityAuditEvent {\n");

        sb.append("    action: ").append(toIndentedString(action)).append("\n");
        sb.append("    commitVersion: ").append(toIndentedString(commitVersion)).append("\n");
        sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
        sb.append("    entityType: ").append(toIndentedString(entityType)).append("\n");
        sb.append("    entityValue: ").append(toIndentedString(entityValue)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
        sb.append("    modifiedDate: ").append(toIndentedString(modifiedDate)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

