/**
 * PodcastModern API
 * PodcastModern API documentation
 * <p>
 * OpenAPI spec version: 0.0.1
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.javathlon.apiclient.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;


/**
 * ProfileInfoResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T13:50:52.801+04:00")
public class ProfileInfoResponse {
    @SerializedName("activeProfiles")
    private List<String> activeProfiles = new ArrayList<String>();

    @SerializedName("ribbonEnv")
    private String ribbonEnv = null;

    public ProfileInfoResponse activeProfiles(List<String> activeProfiles) {
        this.activeProfiles = activeProfiles;
        return this;
    }

    public ProfileInfoResponse addActiveProfilesItem(String activeProfilesItem) {
        this.activeProfiles.add(activeProfilesItem);
        return this;
    }

    /**
     * Get activeProfiles
     * @return activeProfiles
     **/
    @ApiModelProperty(example = "null", value = "")
    public List<String> getActiveProfiles() {
        return activeProfiles;
    }

    public void setActiveProfiles(List<String> activeProfiles) {
        this.activeProfiles = activeProfiles;
    }

    public ProfileInfoResponse ribbonEnv(String ribbonEnv) {
        this.ribbonEnv = ribbonEnv;
        return this;
    }

    /**
     * Get ribbonEnv
     * @return ribbonEnv
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getRibbonEnv() {
        return ribbonEnv;
    }

    public void setRibbonEnv(String ribbonEnv) {
        this.ribbonEnv = ribbonEnv;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ProfileInfoResponse profileInfoResponse = (ProfileInfoResponse) o;
        return Objects.equals(this.activeProfiles, profileInfoResponse.activeProfiles) &&
                Objects.equals(this.ribbonEnv, profileInfoResponse.ribbonEnv);
    }

    @Override
    public int hashCode() {
        return Objects.hash(activeProfiles, ribbonEnv);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ProfileInfoResponse {\n");

        sb.append("    activeProfiles: ").append(toIndentedString(activeProfiles)).append("\n");
        sb.append("    ribbonEnv: ").append(toIndentedString(ribbonEnv)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

