/**
 * PodcastModern API
 * PodcastModern API documentation
 * <p>
 * OpenAPI spec version: 0.0.1
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.javathlon.apiclient.model;

import com.google.gson.annotations.SerializedName;

import org.joda.time.DateTime;
import org.joda.time.LocalDate;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;


/**
 * SubscriptionItemDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T13:50:52.801+04:00")
public class SubscriptionItemDTO {
    @SerializedName("applications")
    private List<ApplicationDTO> applications = new ArrayList<ApplicationDTO>();

    @SerializedName("createdBy")
    private String createdBy = null;

    @SerializedName("createdDate")
    private DateTime createdDate = null;

    @SerializedName("description")
    private String description = null;

    @SerializedName("durationDay")
    private Integer durationDay = null;

    @SerializedName("endDate")
    private LocalDate endDate = null;

    @SerializedName("id")
    private Long id = null;

    @SerializedName("lastModifiedBy")
    private String lastModifiedBy = null;

    @SerializedName("lastModifiedDate")
    private DateTime lastModifiedDate = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("podcasts")
    private List<PodcastDTO> podcasts = new ArrayList<PodcastDTO>();

    @SerializedName("price")
    private Double price = null;

    @SerializedName("skuName")
    private String skuName = null;

    @SerializedName("startDate")
    private LocalDate startDate = null;

    public SubscriptionItemDTO applications(List<ApplicationDTO> applications) {
        this.applications = applications;
        return this;
    }

    public SubscriptionItemDTO addApplicationsItem(ApplicationDTO applicationsItem) {
        this.applications.add(applicationsItem);
        return this;
    }

    /**
     * Get applications
     * @return applications
     **/
    @ApiModelProperty(example = "null", value = "")
    public List<ApplicationDTO> getApplications() {
        return applications;
    }

    public void setApplications(List<ApplicationDTO> applications) {
        this.applications = applications;
    }

    public SubscriptionItemDTO createdBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Get createdBy
     * @return createdBy
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public SubscriptionItemDTO createdDate(DateTime createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Get createdDate
     * @return createdDate
     **/
    @ApiModelProperty(example = "null", value = "")
    public DateTime getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(DateTime createdDate) {
        this.createdDate = createdDate;
    }

    public SubscriptionItemDTO description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     * @return description
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public SubscriptionItemDTO durationDay(Integer durationDay) {
        this.durationDay = durationDay;
        return this;
    }

    /**
     * Get durationDay
     * @return durationDay
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getDurationDay() {
        return durationDay;
    }

    public void setDurationDay(Integer durationDay) {
        this.durationDay = durationDay;
    }

    public SubscriptionItemDTO endDate(LocalDate endDate) {
        this.endDate = endDate;
        return this;
    }

    /**
     * Get endDate
     * @return endDate
     **/
    @ApiModelProperty(example = "null", value = "")
    public LocalDate getEndDate() {
        return endDate;
    }

    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    public SubscriptionItemDTO id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * @return id
     **/
    @ApiModelProperty(example = "null", value = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public SubscriptionItemDTO lastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
        return this;
    }

    /**
     * Get lastModifiedBy
     * @return lastModifiedBy
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public SubscriptionItemDTO lastModifiedDate(DateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
        return this;
    }

    /**
     * Get lastModifiedDate
     * @return lastModifiedDate
     **/
    @ApiModelProperty(example = "null", value = "")
    public DateTime getLastModifiedDate() {
        return lastModifiedDate;
    }

    public void setLastModifiedDate(DateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    public SubscriptionItemDTO name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     * @return name
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public SubscriptionItemDTO podcasts(List<PodcastDTO> podcasts) {
        this.podcasts = podcasts;
        return this;
    }

    public SubscriptionItemDTO addPodcastsItem(PodcastDTO podcastsItem) {
        this.podcasts.add(podcastsItem);
        return this;
    }

    /**
     * Get podcasts
     * @return podcasts
     **/
    @ApiModelProperty(example = "null", value = "")
    public List<PodcastDTO> getPodcasts() {
        return podcasts;
    }

    public void setPodcasts(List<PodcastDTO> podcasts) {
        this.podcasts = podcasts;
    }

    public SubscriptionItemDTO price(Double price) {
        this.price = price;
        return this;
    }

    /**
     * Get price
     * @return price
     **/
    @ApiModelProperty(example = "null", value = "")
    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public SubscriptionItemDTO skuName(String skuName) {
        this.skuName = skuName;
        return this;
    }

    /**
     * Get skuName
     * @return skuName
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getSkuName() {
        return skuName;
    }

    public void setSkuName(String skuName) {
        this.skuName = skuName;
    }

    public SubscriptionItemDTO startDate(LocalDate startDate) {
        this.startDate = startDate;
        return this;
    }

    /**
     * Get startDate
     * @return startDate
     **/
    @ApiModelProperty(example = "null", value = "")
    public LocalDate getStartDate() {
        return startDate;
    }

    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubscriptionItemDTO subscriptionItemDTO = (SubscriptionItemDTO) o;
        return Objects.equals(this.applications, subscriptionItemDTO.applications) &&
                Objects.equals(this.createdBy, subscriptionItemDTO.createdBy) &&
                Objects.equals(this.createdDate, subscriptionItemDTO.createdDate) &&
                Objects.equals(this.description, subscriptionItemDTO.description) &&
                Objects.equals(this.durationDay, subscriptionItemDTO.durationDay) &&
                Objects.equals(this.endDate, subscriptionItemDTO.endDate) &&
                Objects.equals(this.id, subscriptionItemDTO.id) &&
                Objects.equals(this.lastModifiedBy, subscriptionItemDTO.lastModifiedBy) &&
                Objects.equals(this.lastModifiedDate, subscriptionItemDTO.lastModifiedDate) &&
                Objects.equals(this.name, subscriptionItemDTO.name) &&
                Objects.equals(this.podcasts, subscriptionItemDTO.podcasts) &&
                Objects.equals(this.price, subscriptionItemDTO.price) &&
                Objects.equals(this.skuName, subscriptionItemDTO.skuName) &&
                Objects.equals(this.startDate, subscriptionItemDTO.startDate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(applications, createdBy, createdDate, description, durationDay, endDate, id, lastModifiedBy, lastModifiedDate, name, podcasts, price, skuName, startDate);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SubscriptionItemDTO {\n");

        sb.append("    applications: ").append(toIndentedString(applications)).append("\n");
        sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
        sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    durationDay: ").append(toIndentedString(durationDay)).append("\n");
        sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
        sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    podcasts: ").append(toIndentedString(podcasts)).append("\n");
        sb.append("    price: ").append(toIndentedString(price)).append("\n");
        sb.append("    skuName: ").append(toIndentedString(skuName)).append("\n");
        sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

