/**
 * PodcastModern API
 * PodcastModern API documentation
 * <p>
 * OpenAPI spec version: 0.0.1
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.javathlon.apiclient.model;

import com.google.gson.annotations.SerializedName;

import org.joda.time.DateTime;
import org.joda.time.LocalDate;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;


/**
 * Subscription
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-05T16:35:00.407+04:00")
public class Subscription {
    @SerializedName("application")
    private Application application = null;

    @SerializedName("createdBy")
    private String createdBy = null;

    @SerializedName("createdDate")
    private DateTime createdDate = null;

    @SerializedName("currency")
    private String currency = null;

    @SerializedName("id")
    private Long id = null;

    @SerializedName("lastModifiedBy")
    private String lastModifiedBy = null;

    @SerializedName("lastModifiedDate")
    private DateTime lastModifiedDate = null;

    @SerializedName("memberType")
    private String memberType = null;

    @SerializedName("payload")
    private String payload = null;

    @SerializedName("price")
    private Float price = null;

    @SerializedName("refreshCount")
    private Long refreshCount = null;

    @SerializedName("refreshPeriod")
    private String refreshPeriod = null;

    @SerializedName("subscriptionDate")
    private LocalDate subscriptionDate = null;

    @SerializedName("subscriptionId")
    private Long subscriptionId = null;

    @SerializedName("subscriptionItem")
    private String subscriptionItem = null;

    @SerializedName("trialEndDate")
    private LocalDate trialEndDate = null;

    @SerializedName("user")
    private User user = null;

    public Subscription application(Application application) {
        this.application = application;
        return this;
    }

    /**
     * Get application
     * @return application
     **/
    @ApiModelProperty(example = "null", value = "")
    public Application getApplication() {
        return application;
    }

    public void setApplication(Application application) {
        this.application = application;
    }

    public Subscription createdBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Get createdBy
     * @return createdBy
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Subscription createdDate(DateTime createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Get createdDate
     * @return createdDate
     **/
    @ApiModelProperty(example = "null", value = "")
    public DateTime getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(DateTime createdDate) {
        this.createdDate = createdDate;
    }

    public Subscription currency(String currency) {
        this.currency = currency;
        return this;
    }

    /**
     * Get currency
     * @return currency
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public Subscription id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * @return id
     **/
    @ApiModelProperty(example = "null", value = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Subscription lastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
        return this;
    }

    /**
     * Get lastModifiedBy
     * @return lastModifiedBy
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Subscription lastModifiedDate(DateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
        return this;
    }

    /**
     * Get lastModifiedDate
     * @return lastModifiedDate
     **/
    @ApiModelProperty(example = "null", value = "")
    public DateTime getLastModifiedDate() {
        return lastModifiedDate;
    }

    public void setLastModifiedDate(DateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    public Subscription memberType(String memberType) {
        this.memberType = memberType;
        return this;
    }

    /**
     * Get memberType
     * @return memberType
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getMemberType() {
        return memberType;
    }

    public void setMemberType(String memberType) {
        this.memberType = memberType;
    }

    public Subscription payload(String payload) {
        this.payload = payload;
        return this;
    }

    /**
     * Get payload
     * @return payload
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getPayload() {
        return payload;
    }

    public void setPayload(String payload) {
        this.payload = payload;
    }

    public Subscription price(Float price) {
        this.price = price;
        return this;
    }

    /**
     * Get price
     * @return price
     **/
    @ApiModelProperty(example = "null", value = "")
    public Float getPrice() {
        return price;
    }

    public void setPrice(Float price) {
        this.price = price;
    }

    public Subscription refreshCount(Long refreshCount) {
        this.refreshCount = refreshCount;
        return this;
    }

    /**
     * Get refreshCount
     * @return refreshCount
     **/
    @ApiModelProperty(example = "null", value = "")
    public Long getRefreshCount() {
        return refreshCount;
    }

    public void setRefreshCount(Long refreshCount) {
        this.refreshCount = refreshCount;
    }

    public Subscription refreshPeriod(String refreshPeriod) {
        this.refreshPeriod = refreshPeriod;
        return this;
    }

    /**
     * Get refreshPeriod
     * @return refreshPeriod
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getRefreshPeriod() {
        return refreshPeriod;
    }

    public void setRefreshPeriod(String refreshPeriod) {
        this.refreshPeriod = refreshPeriod;
    }

    public Subscription subscriptionDate(LocalDate subscriptionDate) {
        this.subscriptionDate = subscriptionDate;
        return this;
    }

    /**
     * Get subscriptionDate
     * @return subscriptionDate
     **/
    @ApiModelProperty(example = "null", value = "")
    public LocalDate getSubscriptionDate() {
        return subscriptionDate;
    }

    public void setSubscriptionDate(LocalDate subscriptionDate) {
        this.subscriptionDate = subscriptionDate;
    }

    public Subscription subscriptionId(Long subscriptionId) {
        this.subscriptionId = subscriptionId;
        return this;
    }

    /**
     * Get subscriptionId
     * @return subscriptionId
     **/
    @ApiModelProperty(example = "null", value = "")
    public Long getSubscriptionId() {
        return subscriptionId;
    }

    public void setSubscriptionId(Long subscriptionId) {
        this.subscriptionId = subscriptionId;
    }

    public Subscription subscriptionItem(String subscriptionItem) {
        this.subscriptionItem = subscriptionItem;
        return this;
    }

    /**
     * Get subscriptionItem
     * @return subscriptionItem
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getSubscriptionItem() {
        return subscriptionItem;
    }

    public void setSubscriptionItem(String subscriptionItem) {
        this.subscriptionItem = subscriptionItem;
    }

    public Subscription trialEndDate(LocalDate trialEndDate) {
        this.trialEndDate = trialEndDate;
        return this;
    }

    /**
     * Get trialEndDate
     * @return trialEndDate
     **/
    @ApiModelProperty(example = "null", value = "")
    public LocalDate getTrialEndDate() {
        return trialEndDate;
    }

    public void setTrialEndDate(LocalDate trialEndDate) {
        this.trialEndDate = trialEndDate;
    }

    public Subscription user(User user) {
        this.user = user;
        return this;
    }

    /**
     * Get user
     * @return user
     **/
    @ApiModelProperty(example = "null", value = "")
    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Subscription subscription = (Subscription) o;
        return Objects.equals(this.application, subscription.application) &&
                Objects.equals(this.createdBy, subscription.createdBy) &&
                Objects.equals(this.createdDate, subscription.createdDate) &&
                Objects.equals(this.currency, subscription.currency) &&
                Objects.equals(this.id, subscription.id) &&
                Objects.equals(this.lastModifiedBy, subscription.lastModifiedBy) &&
                Objects.equals(this.lastModifiedDate, subscription.lastModifiedDate) &&
                Objects.equals(this.memberType, subscription.memberType) &&
                Objects.equals(this.payload, subscription.payload) &&
                Objects.equals(this.price, subscription.price) &&
                Objects.equals(this.refreshCount, subscription.refreshCount) &&
                Objects.equals(this.refreshPeriod, subscription.refreshPeriod) &&
                Objects.equals(this.subscriptionDate, subscription.subscriptionDate) &&
                Objects.equals(this.subscriptionId, subscription.subscriptionId) &&
                Objects.equals(this.subscriptionItem, subscription.subscriptionItem) &&
                Objects.equals(this.trialEndDate, subscription.trialEndDate) &&
                Objects.equals(this.user, subscription.user);
    }

    @Override
    public int hashCode() {
        return Objects.hash(application, createdBy, createdDate, currency, id, lastModifiedBy, lastModifiedDate, memberType, payload, price, refreshCount, refreshPeriod, subscriptionDate, subscriptionId, subscriptionItem, trialEndDate, user);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Subscription {\n");

        sb.append("    application: ").append(toIndentedString(application)).append("\n");
        sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
        sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
        sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
        sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");
        sb.append("    memberType: ").append(toIndentedString(memberType)).append("\n");
        sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
        sb.append("    price: ").append(toIndentedString(price)).append("\n");
        sb.append("    refreshCount: ").append(toIndentedString(refreshCount)).append("\n");
        sb.append("    refreshPeriod: ").append(toIndentedString(refreshPeriod)).append("\n");
        sb.append("    subscriptionDate: ").append(toIndentedString(subscriptionDate)).append("\n");
        sb.append("    subscriptionId: ").append(toIndentedString(subscriptionId)).append("\n");
        sb.append("    subscriptionItem: ").append(toIndentedString(subscriptionItem)).append("\n");
        sb.append("    trialEndDate: ").append(toIndentedString(trialEndDate)).append("\n");
        sb.append("    user: ").append(toIndentedString(user)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

