/**
 * PodcastModern API
 * PodcastModern API documentation
 * <p>
 * OpenAPI spec version: 0.0.1
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.javathlon.apiclient.model;

import com.google.gson.annotations.SerializedName;

import org.joda.time.DateTime;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;


/**
 * SubscriberDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T13:50:52.801+04:00")
public class SubscriberDTO {
    @SerializedName("apnsToken")
    private String apnsToken = null;

    @SerializedName("country")
    private String country = null;

    @SerializedName("createdBy")
    private String createdBy = null;

    @SerializedName("createdDate")
    private DateTime createdDate = null;

    @SerializedName("email")
    private String email = null;

    @SerializedName("gcmToken")
    private String gcmToken = null;

    @SerializedName("gender")
    private String gender = null;

    @SerializedName("googleId")
    private String googleId = null;

    @SerializedName("id")
    private Long id = null;

    @SerializedName("language")
    private String language = null;

    @SerializedName("lastModifiedBy")
    private String lastModifiedBy = null;

    @SerializedName("lastModifiedDate")
    private DateTime lastModifiedDate = null;

    @SerializedName("maxAge")
    private Integer maxAge = null;

    @SerializedName("minAge")
    private Integer minAge = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("serviceName")
    private String serviceName = null;

    @SerializedName("surname")
    private String surname = null;

    @SerializedName("userId")
    private Long userId = null;

    public SubscriberDTO apnsToken(String apnsToken) {
        this.apnsToken = apnsToken;
        return this;
    }

    /**
     * Get apnsToken
     * @return apnsToken
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getApnsToken() {
        return apnsToken;
    }

    public void setApnsToken(String apnsToken) {
        this.apnsToken = apnsToken;
    }

    public SubscriberDTO country(String country) {
        this.country = country;
        return this;
    }

    /**
     * Get country
     * @return country
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public SubscriberDTO createdBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Get createdBy
     * @return createdBy
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public SubscriberDTO createdDate(DateTime createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Get createdDate
     * @return createdDate
     **/
    @ApiModelProperty(example = "null", value = "")
    public DateTime getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(DateTime createdDate) {
        this.createdDate = createdDate;
    }

    public SubscriberDTO email(String email) {
        this.email = email;
        return this;
    }

    /**
     * Get email
     * @return email
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public SubscriberDTO gcmToken(String gcmToken) {
        this.gcmToken = gcmToken;
        return this;
    }

    /**
     * Get gcmToken
     * @return gcmToken
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getGcmToken() {
        return gcmToken;
    }

    public void setGcmToken(String gcmToken) {
        this.gcmToken = gcmToken;
    }

    public SubscriberDTO gender(String gender) {
        this.gender = gender;
        return this;
    }

    /**
     * Get gender
     * @return gender
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public SubscriberDTO googleId(String googleId) {
        this.googleId = googleId;
        return this;
    }

    /**
     * Get googleId
     * @return googleId
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getGoogleId() {
        return googleId;
    }

    public void setGoogleId(String googleId) {
        this.googleId = googleId;
    }

    public SubscriberDTO id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * @return id
     **/
    @ApiModelProperty(example = "null", value = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public SubscriberDTO language(String language) {
        this.language = language;
        return this;
    }

    /**
     * Get language
     * @return language
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public SubscriberDTO lastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
        return this;
    }

    /**
     * Get lastModifiedBy
     * @return lastModifiedBy
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public SubscriberDTO lastModifiedDate(DateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
        return this;
    }

    /**
     * Get lastModifiedDate
     * @return lastModifiedDate
     **/
    @ApiModelProperty(example = "null", value = "")
    public DateTime getLastModifiedDate() {
        return lastModifiedDate;
    }

    public void setLastModifiedDate(DateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    public SubscriberDTO maxAge(Integer maxAge) {
        this.maxAge = maxAge;
        return this;
    }

    /**
     * Get maxAge
     * @return maxAge
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getMaxAge() {
        return maxAge;
    }

    public void setMaxAge(Integer maxAge) {
        this.maxAge = maxAge;
    }

    public SubscriberDTO minAge(Integer minAge) {
        this.minAge = minAge;
        return this;
    }

    /**
     * Get minAge
     * @return minAge
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getMinAge() {
        return minAge;
    }

    public void setMinAge(Integer minAge) {
        this.minAge = minAge;
    }

    public SubscriberDTO name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     * @return name
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public SubscriberDTO serviceName(String serviceName) {
        this.serviceName = serviceName;
        return this;
    }

    /**
     * Get serviceName
     * @return serviceName
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getServiceName() {
        return serviceName;
    }

    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    public SubscriberDTO surname(String surname) {
        this.surname = surname;
        return this;
    }

    /**
     * Get surname
     * @return surname
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public SubscriberDTO userId(Long userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Get userId
     * @return userId
     **/
    @ApiModelProperty(example = "null", value = "")
    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SubscriberDTO subscriberDTO = (SubscriberDTO) o;
        return Objects.equals(this.apnsToken, subscriberDTO.apnsToken) &&
                Objects.equals(this.country, subscriberDTO.country) &&
                Objects.equals(this.createdBy, subscriberDTO.createdBy) &&
                Objects.equals(this.createdDate, subscriberDTO.createdDate) &&
                Objects.equals(this.email, subscriberDTO.email) &&
                Objects.equals(this.gcmToken, subscriberDTO.gcmToken) &&
                Objects.equals(this.gender, subscriberDTO.gender) &&
                Objects.equals(this.googleId, subscriberDTO.googleId) &&
                Objects.equals(this.id, subscriberDTO.id) &&
                Objects.equals(this.language, subscriberDTO.language) &&
                Objects.equals(this.lastModifiedBy, subscriberDTO.lastModifiedBy) &&
                Objects.equals(this.lastModifiedDate, subscriberDTO.lastModifiedDate) &&
                Objects.equals(this.maxAge, subscriberDTO.maxAge) &&
                Objects.equals(this.minAge, subscriberDTO.minAge) &&
                Objects.equals(this.name, subscriberDTO.name) &&
                Objects.equals(this.serviceName, subscriberDTO.serviceName) &&
                Objects.equals(this.surname, subscriberDTO.surname) &&
                Objects.equals(this.userId, subscriberDTO.userId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(apnsToken, country, createdBy, createdDate, email, gcmToken, gender, googleId, id, language, lastModifiedBy, lastModifiedDate, maxAge, minAge, name, serviceName, surname, userId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SubscriberDTO {\n");

        sb.append("    apnsToken: ").append(toIndentedString(apnsToken)).append("\n");
        sb.append("    country: ").append(toIndentedString(country)).append("\n");
        sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
        sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
        sb.append("    email: ").append(toIndentedString(email)).append("\n");
        sb.append("    gcmToken: ").append(toIndentedString(gcmToken)).append("\n");
        sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
        sb.append("    googleId: ").append(toIndentedString(googleId)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    language: ").append(toIndentedString(language)).append("\n");
        sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
        sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");
        sb.append("    maxAge: ").append(toIndentedString(maxAge)).append("\n");
        sb.append("    minAge: ").append(toIndentedString(minAge)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    serviceName: ").append(toIndentedString(serviceName)).append("\n");
        sb.append("    surname: ").append(toIndentedString(surname)).append("\n");
        sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

