/**
 * PodcastModern API
 * PodcastModern API documentation
 * <p>
 * OpenAPI spec version: 0.0.1
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.javathlon.apiclient.model;

import com.google.gson.annotations.SerializedName;

import org.joda.time.DateTime;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;


/**
 * Subscriber
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-05T16:35:00.407+04:00")
public class Subscriber {
    @SerializedName("apnsToken")
    private String apnsToken = null;

    @SerializedName("country")
    private String country = null;

    @SerializedName("createdBy")
    private String createdBy = null;

    @SerializedName("createdDate")
    private DateTime createdDate = null;

    @SerializedName("email")
    private String email = null;

    @SerializedName("gcmToken")
    private String gcmToken = null;

    @SerializedName("gender")
    private String gender = null;

    @SerializedName("id")
    private Long id = null;

    @SerializedName("language")
    private String language = null;

    @SerializedName("lastModifiedBy")
    private String lastModifiedBy = null;

    @SerializedName("lastModifiedDate")
    private DateTime lastModifiedDate = null;

    @SerializedName("maxAge")
    private Integer maxAge = null;

    @SerializedName("minAge")
    private Integer minAge = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("surname")
    private String surname = null;

    @SerializedName("servicename")
    private String serviceName;

    @SerializedName("googleid")
    private String googleid = null;

    public Subscriber apnsToken(String apnsToken) {
        this.apnsToken = apnsToken;
        return this;
    }

    /**
     * Get apnsToken
     * @return apnsToken
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getApnsToken() {
        return apnsToken;
    }

    public void setApnsToken(String apnsToken) {
        this.apnsToken = apnsToken;
    }

    public Subscriber country(String country) {
        this.country = country;
        return this;
    }

    /**
     * Get country
     * @return country
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public Subscriber createdBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Get createdBy
     * @return createdBy
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Subscriber createdDate(DateTime createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Get createdDate
     * @return createdDate
     **/
    @ApiModelProperty(example = "null", value = "")
    public DateTime getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(DateTime createdDate) {
        this.createdDate = createdDate;
    }

    public Subscriber email(String email) {
        this.email = email;
        return this;
    }

    /**
     * Get email
     * @return email
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Subscriber gcmToken(String gcmToken) {
        this.gcmToken = gcmToken;
        return this;
    }

    /**
     * Get gcmToken
     * @return gcmToken
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getGcmToken() {
        return gcmToken;
    }

    public void setGcmToken(String gcmToken) {
        this.gcmToken = gcmToken;
    }

    public Subscriber gender(String gender) {
        this.gender = gender;
        return this;
    }

    /**
     * Get gender
     * @return gender
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public Subscriber id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * @return id
     **/
    @ApiModelProperty(example = "null", value = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Subscriber language(String language) {
        this.language = language;
        return this;
    }

    /**
     * Get language
     * @return language
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public Subscriber lastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
        return this;
    }

    /**
     * Get lastModifiedBy
     * @return lastModifiedBy
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Subscriber lastModifiedDate(DateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
        return this;
    }

    /**
     * Get lastModifiedDate
     * @return lastModifiedDate
     **/
    @ApiModelProperty(example = "null", value = "")
    public DateTime getLastModifiedDate() {
        return lastModifiedDate;
    }

    public void setLastModifiedDate(DateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    public Subscriber maxAge(Integer maxAge) {
        this.maxAge = maxAge;
        return this;
    }

    /**
     * Get maxAge
     * @return maxAge
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getMaxAge() {
        return maxAge;
    }

    public void setMaxAge(Integer maxAge) {
        this.maxAge = maxAge;
    }

    public Subscriber minAge(Integer minAge) {
        this.minAge = minAge;
        return this;
    }

    /**
     * Get minAge
     * @return minAge
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getMinAge() {
        return minAge;
    }

    public void setMinAge(Integer minAge) {
        this.minAge = minAge;
    }

    public Subscriber name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     * @return name
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Subscriber surname(String surname) {
        this.surname = surname;
        return this;
    }

    /**
     * Get surname
     * @return surname
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }


    public String getGoogleid() {
        return googleid;
    }

    public void setGoogleid(String googleid) {
        this.googleid = googleid;
    }

    public String getServiceName() {
        return serviceName;
    }

    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Subscriber subscriber = (Subscriber) o;
        return Objects.equals(this.apnsToken, subscriber.apnsToken) &&
                Objects.equals(this.country, subscriber.country) &&
                Objects.equals(this.createdBy, subscriber.createdBy) &&
                Objects.equals(this.createdDate, subscriber.createdDate) &&
                Objects.equals(this.email, subscriber.email) &&
                Objects.equals(this.gcmToken, subscriber.gcmToken) &&
                Objects.equals(this.gender, subscriber.gender) &&
                Objects.equals(this.id, subscriber.id) &&
                Objects.equals(this.language, subscriber.language) &&
                Objects.equals(this.lastModifiedBy, subscriber.lastModifiedBy) &&
                Objects.equals(this.lastModifiedDate, subscriber.lastModifiedDate) &&
                Objects.equals(this.maxAge, subscriber.maxAge) &&
                Objects.equals(this.minAge, subscriber.minAge) &&
                Objects.equals(this.name, subscriber.name) &&
                Objects.equals(this.surname, subscriber.surname);
    }

    @Override
    public int hashCode() {
        return Objects.hash(apnsToken, country, createdBy, createdDate, email, gcmToken, gender, id, language, lastModifiedBy, lastModifiedDate, maxAge, minAge, name, surname);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Subscriber {\n");

        sb.append("    apnsToken: ").append(toIndentedString(apnsToken)).append("\n");
        sb.append("    country: ").append(toIndentedString(country)).append("\n");
        sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
        sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
        sb.append("    email: ").append(toIndentedString(email)).append("\n");
        sb.append("    gcmToken: ").append(toIndentedString(gcmToken)).append("\n");
        sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    language: ").append(toIndentedString(language)).append("\n");
        sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
        sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");
        sb.append("    maxAge: ").append(toIndentedString(maxAge)).append("\n");
        sb.append("    minAge: ").append(toIndentedString(minAge)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    surname: ").append(toIndentedString(surname)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

