/**
 * PodcastModern API
 * PodcastModern API documentation
 * <p>
 * OpenAPI spec version: 0.0.1
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.javathlon.apiclient.model;

import com.google.gson.annotations.SerializedName;

import org.joda.time.DateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;


/**
 * User
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T13:50:52.801+04:00")
public class User {
    @SerializedName("activated")
    private Boolean activated = null;

    @SerializedName("createdBy")
    private String createdBy = null;

    @SerializedName("createdDate")
    private DateTime createdDate = null;

    @SerializedName("email")
    private String email = null;

    @SerializedName("firstName")
    private String firstName = null;

    @SerializedName("id")
    private Long id = null;

    @SerializedName("langKey")
    private String langKey = null;

    @SerializedName("lastModifiedBy")
    private String lastModifiedBy = null;

    @SerializedName("lastModifiedDate")
    private DateTime lastModifiedDate = null;

    @SerializedName("lastName")
    private String lastName = null;

    @SerializedName("login")
    private String login = null;

    @SerializedName("ownedApplications")
    private List<Application> ownedApplications = new ArrayList<Application>();

    @SerializedName("resetDate")
    private DateTime resetDate = null;

    @SerializedName("resetKey")
    private String resetKey = null;

    public User activated(Boolean activated) {
        this.activated = activated;
        return this;
    }

    /**
     * Get activated
     * @return activated
     **/
    @ApiModelProperty(example = "null", required = true, value = "")
    public Boolean getActivated() {
        return activated;
    }

    public void setActivated(Boolean activated) {
        this.activated = activated;
    }

    public User createdBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Get createdBy
     * @return createdBy
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public User createdDate(DateTime createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Get createdDate
     * @return createdDate
     **/
    @ApiModelProperty(example = "null", value = "")
    public DateTime getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(DateTime createdDate) {
        this.createdDate = createdDate;
    }

    public User email(String email) {
        this.email = email;
        return this;
    }

    /**
     * Get email
     * @return email
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public User firstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    /**
     * Get firstName
     * @return firstName
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public User id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * @return id
     **/
    @ApiModelProperty(example = "null", value = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public User langKey(String langKey) {
        this.langKey = langKey;
        return this;
    }

    /**
     * Get langKey
     * @return langKey
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getLangKey() {
        return langKey;
    }

    public void setLangKey(String langKey) {
        this.langKey = langKey;
    }

    public User lastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
        return this;
    }

    /**
     * Get lastModifiedBy
     * @return lastModifiedBy
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public User lastModifiedDate(DateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
        return this;
    }

    /**
     * Get lastModifiedDate
     * @return lastModifiedDate
     **/
    @ApiModelProperty(example = "null", value = "")
    public DateTime getLastModifiedDate() {
        return lastModifiedDate;
    }

    public void setLastModifiedDate(DateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    public User lastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    /**
     * Get lastName
     * @return lastName
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public User login(String login) {
        this.login = login;
        return this;
    }

    /**
     * Get login
     * @return login
     **/
    @ApiModelProperty(example = "null", required = true, value = "")
    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public User ownedApplications(List<Application> ownedApplications) {
        this.ownedApplications = ownedApplications;
        return this;
    }

    public User addOwnedApplicationsItem(Application ownedApplicationsItem) {
        this.ownedApplications.add(ownedApplicationsItem);
        return this;
    }

    /**
     * Get ownedApplications
     * @return ownedApplications
     **/
    @ApiModelProperty(example = "null", value = "")
    public List<Application> getOwnedApplications() {
        return ownedApplications;
    }

    public void setOwnedApplications(List<Application> ownedApplications) {
        this.ownedApplications = ownedApplications;
    }

    public User resetDate(DateTime resetDate) {
        this.resetDate = resetDate;
        return this;
    }

    /**
     * Get resetDate
     * @return resetDate
     **/
    @ApiModelProperty(example = "null", value = "")
    public DateTime getResetDate() {
        return resetDate;
    }

    public void setResetDate(DateTime resetDate) {
        this.resetDate = resetDate;
    }

    public User resetKey(String resetKey) {
        this.resetKey = resetKey;
        return this;
    }

    /**
     * Get resetKey
     * @return resetKey
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getResetKey() {
        return resetKey;
    }

    public void setResetKey(String resetKey) {
        this.resetKey = resetKey;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        User user = (User) o;
        return Objects.equals(this.activated, user.activated) &&
                Objects.equals(this.createdBy, user.createdBy) &&
                Objects.equals(this.createdDate, user.createdDate) &&
                Objects.equals(this.email, user.email) &&
                Objects.equals(this.firstName, user.firstName) &&
                Objects.equals(this.id, user.id) &&
                Objects.equals(this.langKey, user.langKey) &&
                Objects.equals(this.lastModifiedBy, user.lastModifiedBy) &&
                Objects.equals(this.lastModifiedDate, user.lastModifiedDate) &&
                Objects.equals(this.lastName, user.lastName) &&
                Objects.equals(this.login, user.login) &&
                Objects.equals(this.ownedApplications, user.ownedApplications) &&
                Objects.equals(this.resetDate, user.resetDate) &&
                Objects.equals(this.resetKey, user.resetKey);
    }

    @Override
    public int hashCode() {
        return Objects.hash(activated, createdBy, createdDate, email, firstName, id, langKey, lastModifiedBy, lastModifiedDate, lastName, login, ownedApplications, resetDate, resetKey);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class User {\n");

        sb.append("    activated: ").append(toIndentedString(activated)).append("\n");
        sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
        sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
        sb.append("    email: ").append(toIndentedString(email)).append("\n");
        sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    langKey: ").append(toIndentedString(langKey)).append("\n");
        sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
        sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");
        sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
        sb.append("    login: ").append(toIndentedString(login)).append("\n");
        sb.append("    ownedApplications: ").append(toIndentedString(ownedApplications)).append("\n");
        sb.append("    resetDate: ").append(toIndentedString(resetDate)).append("\n");
        sb.append("    resetKey: ").append(toIndentedString(resetKey)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

