/**
 * PodcastModern API
 * PodcastModern API documentation
 * <p>
 * OpenAPI spec version: 0.0.1
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.javathlon.apiclient.model;

import com.google.gson.annotations.SerializedName;

import org.joda.time.DateTime;
import org.joda.time.LocalDate;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;


/**
 * UserCloudMessagingDTO
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-24T13:50:52.801+04:00")
public class UserCloudMessagingDTO {
    @SerializedName("createdBy")
    private String createdBy = null;

    @SerializedName("createdDate")
    private DateTime createdDate = null;

    @SerializedName("id")
    private Long id = null;

    @SerializedName("isPermitted")
    private Boolean isPermitted = null;

    @SerializedName("lastModifiedBy")
    private String lastModifiedBy = null;

    @SerializedName("lastModifiedDate")
    private DateTime lastModifiedDate = null;

    @SerializedName("lastRefreshDate")
    private LocalDate lastRefreshDate = null;

    @SerializedName("serviceType")
    private String serviceType = null;

    @SerializedName("token")
    private String token = null;

    @SerializedName("userId")
    private Long userId = null;

    public UserCloudMessagingDTO createdBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Get createdBy
     * @return createdBy
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public UserCloudMessagingDTO createdDate(DateTime createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Get createdDate
     * @return createdDate
     **/
    @ApiModelProperty(example = "null", value = "")
    public DateTime getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(DateTime createdDate) {
        this.createdDate = createdDate;
    }

    public UserCloudMessagingDTO id(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * @return id
     **/
    @ApiModelProperty(example = "null", value = "")
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public UserCloudMessagingDTO isPermitted(Boolean isPermitted) {
        this.isPermitted = isPermitted;
        return this;
    }

    /**
     * Get isPermitted
     * @return isPermitted
     **/
    @ApiModelProperty(example = "null", value = "")
    public Boolean getIsPermitted() {
        return isPermitted;
    }

    public void setIsPermitted(Boolean isPermitted) {
        this.isPermitted = isPermitted;
    }

    public UserCloudMessagingDTO lastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
        return this;
    }

    /**
     * Get lastModifiedBy
     * @return lastModifiedBy
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public UserCloudMessagingDTO lastModifiedDate(DateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
        return this;
    }

    /**
     * Get lastModifiedDate
     * @return lastModifiedDate
     **/
    @ApiModelProperty(example = "null", value = "")
    public DateTime getLastModifiedDate() {
        return lastModifiedDate;
    }

    public void setLastModifiedDate(DateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    public UserCloudMessagingDTO lastRefreshDate(LocalDate lastRefreshDate) {
        this.lastRefreshDate = lastRefreshDate;
        return this;
    }

    /**
     * Get lastRefreshDate
     * @return lastRefreshDate
     **/
    @ApiModelProperty(example = "null", value = "")
    public LocalDate getLastRefreshDate() {
        return lastRefreshDate;
    }

    public void setLastRefreshDate(LocalDate lastRefreshDate) {
        this.lastRefreshDate = lastRefreshDate;
    }

    public UserCloudMessagingDTO serviceType(String serviceType) {
        this.serviceType = serviceType;
        return this;
    }

    /**
     * Get serviceType
     * @return serviceType
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getServiceType() {
        return serviceType;
    }

    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }

    public UserCloudMessagingDTO token(String token) {
        this.token = token;
        return this;
    }

    /**
     * Get token
     * @return token
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public UserCloudMessagingDTO userId(Long userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Get userId
     * @return userId
     **/
    @ApiModelProperty(example = "null", value = "")
    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserCloudMessagingDTO userCloudMessagingDTO = (UserCloudMessagingDTO) o;
        return Objects.equals(this.createdBy, userCloudMessagingDTO.createdBy) &&
                Objects.equals(this.createdDate, userCloudMessagingDTO.createdDate) &&
                Objects.equals(this.id, userCloudMessagingDTO.id) &&
                Objects.equals(this.isPermitted, userCloudMessagingDTO.isPermitted) &&
                Objects.equals(this.lastModifiedBy, userCloudMessagingDTO.lastModifiedBy) &&
                Objects.equals(this.lastModifiedDate, userCloudMessagingDTO.lastModifiedDate) &&
                Objects.equals(this.lastRefreshDate, userCloudMessagingDTO.lastRefreshDate) &&
                Objects.equals(this.serviceType, userCloudMessagingDTO.serviceType) &&
                Objects.equals(this.token, userCloudMessagingDTO.token) &&
                Objects.equals(this.userId, userCloudMessagingDTO.userId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(createdBy, createdDate, id, isPermitted, lastModifiedBy, lastModifiedDate, lastRefreshDate, serviceType, token, userId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UserCloudMessagingDTO {\n");

        sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
        sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    isPermitted: ").append(toIndentedString(isPermitted)).append("\n");
        sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");
        sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");
        sb.append("    lastRefreshDate: ").append(toIndentedString(lastRefreshDate)).append("\n");
        sb.append("    serviceType: ").append(toIndentedString(serviceType)).append("\n");
        sb.append("    token: ").append(toIndentedString(token)).append("\n");
        sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

